name: Trigger auto deployment for shopathomeaeeb99d8

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ start ]
    paths:
    - 'api-express/**'
    - '.github/workflows/shopathomeaeeb99d8-AutoDeployTrigger-0d1db055-f60c-4143-a46c-a78455069912.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SHOPATHOMEAEEB99D8_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SHOPATHOMEAEEB99D8_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SHOPATHOMEAEEB99D8_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/api-express 
          registryUrl: 
          registryUsername: ${{ secrets.SHOPATHOMEAEEB99D8_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHOPATHOMEAEEB99D8_REGISTRY_PASSWORD }}
          containerAppName: shopathomeaeeb99d8
          resourceGroup: shopathomeaeeb
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


