name: Trigger auto deployment for shopathomebf9f98a6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ backend-appspaces ]
    paths:
    - 'api/**'
    - '.github/workflows/shopathomebf9f98a6-AutoDeployTrigger-469df216-058f-4c50-892d-dfa7507e0ef4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SHOPATHOMEBF9F98A6_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SHOPATHOMEBF9F98A6_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SHOPATHOMEBF9F98A6_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/api 
          registryUrl: 
          registryUsername: ${{ secrets.SHOPATHOMEBF9F98A6_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHOPATHOMEBF9F98A6_REGISTRY_PASSWORD }}
          containerAppName: shopathomebf9f98a6
          resourceGroup: shopathomebf9f
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


